### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by eagerashwani** [giandifra/flutter-face-contour-plugin#1]
In face_contour_detection

1) line 36
rotationIntToImageRotation(int rotation) → ImageRotation
A value of type 'ImageRotation (where ImageRotation is defined in C:\Users\kal\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.6.0+2\lib\src\firebase_vision.dart)' can't be assigned to a variable of type 'ImageRotation (where ImageRotation is defined in C:\Users\kal\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_face_contour-0.1.0\lib\src\firebase_vision.dart)'.dart(invalid_assignment)

2) line 57
FaceDetector faceDetector
The argument type '(FirebaseVisionImage) → Future<List<Face>>' can't be assigned to the parameter type '(FirebaseVisionImage) → Future<dynamic>'.dart(argument_type_not_assignable)

3) line 57
ImageRotation rotation
The argument type 'ImageRotation (where ImageRotation is defined in C:\Users\kal\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_face_contour-0.1.0\lib\src\firebase_vision.dart)' can't be assigned to the parameter type 'ImageRotation (where ImageRotation is defined in C:\Users\kal\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.6.0+2\lib\src\firebase_vision.dart)'.dart(argument_type_not_assignable)

**Comment by LintonAchmad** [comment]
@therichiekumar you have two ml kit plugins installed in your project. Comment out the one import that you are not going to use.

**Comment by eagerashwani** [comment]
I have these plugins

  firebase_face_contour: ^0.1.0
  camera: ^0.4.2
  firebase_ml_vision:

**Comment by LintonAchmad** [comment]
@therichiekumar comment out firebase_ml_vision plugin or remove it also remove the imports from your code/pages. The firebase_face_contour plugin does the exact same stuff as the firebase_ml_vision plugin.
